### ISSUE TITLE
Implement ECS-Compatibility Mode

### ISSUE THREAD

**Issue by yaauie** [logstash-plugins/logstash-integration-jdbc#19]
_This is a stub issue, and needs to be fleshed out with details specific to
this plugin._

***

As a part of the effort to make plugins able to run in an ECS-Compatible manner
by default in an upcoming release of Logstash, this plugin needs to either
implement an ECS-Compatibility mode or certify that it does not implicitly use
fields that conflict with ECS.

----

Introduce a `target` option that specifies the name of the sub-field where nest the row columns loaded from DB. This option should be populated if ECS support is `not disabled`.

**Comment by andsel** [comment]
@yaauie PR #69 with fixes for JDBC input and PR #71 with fixes for JDBC filter static were published with plugin version `5.1.0`.
For the JDBC filter streaming the `target` is mandatory, so we can close this issue.

**Comment by andsel** [comment]
I close this since with version `5.1.0` of `logstash-integration-jdbc` ship it
