### ISSUE TITLE
make input plugin compatible with sequel fallback possibility from drivermanager to java connect

### ISSUE THREAD

**Issue by 111andre111** [logstash-plugins/logstash-integration-jdbc#30]
For JDBC input plugin (not sure about the other plugins) it seems like for the moment the sequel fallback possibility doesn't work, because there are some JDBC libraries out there that don't autoload or don't work through Drivermanager, but work with normal JDBC connect.
For that exists :driver parameter as an option which can be transferred as class to sequel and the fallback will work.
https://github.com/jeremyevans/sequel/blob/master/doc/opening_databases.rdoc#jdbc--

Here a small test snippet tested with irb:
```
require 'JDBC.jar'
require 'other.jar'
require "java"
require "sequel"
require "sequel/adapters/jdbc"
DBClass=Sequel::JDBC.load_driver('com......jdbc.Driver')
opts = { :user => "", :password => "", :pool_timeout => 5, :keep_reference => false, :driver => DBClass }
url = 'jdbc:..........'
DB = Sequel.connect(url, opts=opts)
DB['SELECT ...'].to_a.inspect
exit()
```
So the important part is this:
`DBClass=Sequel::JDBC.load_driver('com......jdbc.Driver')`
followed by that
`:driver => DBClass`

The relevant part for that in sequel is here:
https://github.com/jeremyevans/sequel/blob/5b5c884d36d40b7aac62bc03bbb1db08795b6297/lib/sequel/adapters/jdbc.rb#L215-L227

Here is still the irb part without Sequel in order to show what happens:
```
require 'JDBC.jar'
require 'other.jar'
require "java"
require "sequel"
require "sequel/adapters/jdbc"
driver = Java::com.....Driver.new
props = java.util.Properties.new
props.setProperty("user", "")
props.setProperty("password", "")
url = 'jdbc:....'
# now drivermanager test
conn = java.sql.DriverManager.get_connection(url)
# Error message No suitable driver found for jdbc:...
# Now try to fallback
conn = driver.connect(url, props)
# => #<Java::Com loaded
stmt = conn.createStatement();
sql = "SELECT count(*) AS COUNT FROM logstashtable";
rs = stmt.executeQuery(sql);
while (rs.next) do
  countname = rs.getString("COUNT");
  puts countname
end
stmt.close
conn.close
```

Now trying to translate that into logstash-input-jdbc code the place where something similar happens is here:
https://github.com/logstash-plugins/logstash-input-jdbc/blob/5b5c884d36d40b7aac62bc03bbb1db08795b6297/lib/logstash/plugin_mixins/jdbc/jdbc.rb#L110-L120

and here:
https://github.com/logstash-plugins/logstash-input-jdbc/blob/master/lib/logstash/plugin_mixins/jdbc/jdbc.rb#L168

Now I tried to move the class load into a variable:
DBClass=Sequel::JDBC.load_driver(@jdbc_driver_class)

and adding the option to the opts section:
https://github.com/jeremyevans/sequel/blob/5b5c884d36d40b7aac62bc03bbb1db08795b6297/lib/sequel/adapters/jdbc.rb#L215
```
:driver => DBClass,
```
But at the moment I get an error `dynamic constant assignment`.

Question: What would be the logstash way to fix that, because I think that happens because this code is inside a method.

The logstash input part is like that:
```
  jdbc {
    jdbc_driver_library => "JDBC.jar,other.jar"
    jdbc_driver_class => "com.....Driver"
    jdbc_connection_string => "jdbc:...."
    jdbc_user => ""
    jdbc_password => ""
    sql_log_level => "debug"
    jdbc_validate_connection => true
    statement => "SELECT * FROM logstashtable"
  }
```

This may be a similar case even:
https://github.com/logstash-plugins/logstash-integration-jdbc/issues/23

**Comment by robbavey** [comment]
@111andre111 Nice find!

The issue with your code snippet is that `DBClass` is a constant, which cannot be defined in methods (variables starting with a capital letter are constants in Ruby).

What is suspect you might want to do is define something like:
`@loaded_driver = Sequel::JDBC.load_driver('com......jdbc.Driver')`

And then add `:driver => @loaded_driver` [https://github.com/logstash-plugins/logstash-input-jdbc/blob/master/lib/logstash/plugin_mixins/jdbc/jdbc.rb#L113](here) to the `opts` hash.
