### ISSUE TITLE
unable to load  jdbc_driver_library

### ISSUE THREAD

**Issue by CrazyQZQ** [logstash-plugins/logstash-integration-jdbc#50]
Error: unable to load /etc/logstash/jdbc/mysql-connector-java-5.1.36-bin.jar from :jdbc_driver_library, file not readable (please check user and group permissions for the path)

**Comment by kares** [comment]
Hey CrazyQZQ, the error message is clear about what the problem is. 
This is usually a permission issue for the user LS is running under.
